# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    asrs_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    asrs_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

asrs_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
asrs_gripper_controller:
  ros__parameters:
    joints:
      - base_to_driver
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity